<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('abilities')->insert([
            [
                'name' => 'AdminSystemSettings-R',
                'title' => 'Can read the admin system settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminSystemSettings-W',
                'title' => 'Can make changes in admin system settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminSystemSettings-D',
                'title' => 'Can make delete operations in admin system settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminUsers-R',
                'title' => 'Can read the admin users tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminUsers-W',
                'title' => 'Can make changes in admin users tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminUsers-D',
                'title' => 'Can make delete operations in admin users tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminPrivilege-R',
                'title' => 'Can read the admin privilege tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminPrivilege-W',
                'title' => 'Can make changes in admin privilege tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminPrivilege-D',
                'title' => 'Can make delete operations in admin privilege tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminIntegration-R',
                'title' => 'Can read the admin integration management tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminIntegration-W',
                'title' => 'Can make changes in admin integration management tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminIntegration-D',
                'title' => 'Can make delete operations in admin integration management tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminSecurity-R',
                'title' => 'Can read the admin security settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminSecurity-W',
                'title' => 'Can make changes in admin security settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AdminSecurity-D',
                'title' => 'Can make delete operations in admin security settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Home-R',
                'title' => 'Can read Home tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Home-W',
                'title' => 'Can make changes in the home tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noticies-R',
                'title' => 'Can read noticies tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noticies-W',
                'title' => 'Can make changes in the noticies tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Noticies-D',
                'title' => 'Can delete the noticies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Subscriptions-R',
                'title' => 'Can read subscriptions tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Subscriptions-W',
                'title' => 'Can make changes in the subscriptions tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Subscriptions-D',
                'title' => 'Can delete the subscriptions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Enforcement-R',
                'title' => 'Can read the enforcement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Enforcement-W',
                'title' => 'Can make changes in the enforcement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Enforcement-D',
                'title' => 'Can make delete operations in the enforcement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZMainSettings-R',
                'title' => 'Can read the ppz main settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZMainSettings-W',
                'title' => 'Can make changes in the ppz main settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZMainSettings-D',
                'title' => 'Can make delete operations in the ppz main settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZDictionaries-R',
                'title' => 'Can read the dictionaries tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZDictionaries-W',
                'title' => 'Can make changes in the ppz dictionaries tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZDictionaries-D',
                'title' => 'Can make delete operations in the ppz dictionaries',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZControlSettings-R',
                'title' => 'Can read the ppz control settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZControlSettings-W',
                'title' => 'Can make changes in the ppz control settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZControlSettings-D',
                'title' => 'Can make delete operations in the ppz control settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZIntegration-R',
                'title' => 'Can read the ppz integration settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZIntegration-W',
                'title' => 'Can make changes in ppz integration settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PPZIntegration-D',
                'title' => 'Can make delete operations in ppz integration settings tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rewarding-R',
                'title' => 'Can read the rewarding tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rewarding-W',
                'title' => 'Can make changes in rewarding tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rewarding-D',
                'title' => 'Can delete the rewardings',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DailySettlement-R',
                'title' => 'Can read the daily settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DailySettlement-W',
                'title' => 'Can make changes in daily settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DailySettlement-D',
                'title' => 'Can make delete operations in daily settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MonthlyQuarterlySettlement-R',
                'title' => 'Can read the monthly and quarterly settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MonthlyQuarterlySettlement-W',
                'title' => 'Can make changes in monthly and quarterly settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MonthlyQuarterlySettlement-D',
                'title' => 'Can make delete operations in monthly and quarterly settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AnnualSettlement-R',
                'title' => 'Can read the annual settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AnnualSettlement-W',
                'title' => 'Can make changes in annual settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AnnualSettlement-D',
                'title' => 'Can make delete operations in annual settlement tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Documents-R',
                'title' => 'Can read the documents and templates tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Documents-W',
                'title' => 'Can make changes in documents and templates tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Documents-D',
                'title' => 'Can make delete operations in documents and templates tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reports-R',
                'title' => 'Can read the reports tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reports-W',
                'title' => 'Can make changes in reports tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reports-D',
                'title' => 'Can make delete operations in reports tab',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MobileControllUser',
                'title' => 'Authorization to conduct mobile telephone inspection',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MobileControllPayments',
                'title' => 'Mobile payment query API entitlement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MobileControllProviding',
                'title' => 'Allows new tickets to be sent and stored in the database',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        DB::table('abilities')->whereIn('name', [
            'AdminSystemSettings-R',
            'AdminSystemSettings-W',
            'AdminSystemSettings-D',
            'AdminUsers-R',
            'AdminUsers-W',
            'AdminUsers-D',
            'AdminPrivilege-R',
            'AdminPrivilege-W',
            'AdminPrivilege-D',
            'AdminIntegration-R',
            'AdminIntegration-W',
            'AdminIntegration-D',
            'AdminSecurity-R',
            'AdminSecurity-W',
            'AdminSecurity-D',
            'Home-R',
            'Home-W',
            'Noticies-R',
            'Noticies-W',
            'Noticies-D',
            'Subscriptions-R',
            'Subscriptions-W',
            'Subscriptions-D',
            'Enforcement-R',
            'Enforcement-W',
            'Enforcement-D',
            'PPZMainSettings-R',
            'PPZMainSettings-W',
            'PPZMainSettings-D',
            'PPZDictionaries-R',
            'PPZDictionaries-W',
            'PPZDictionaries-D',
            'PPZControlSettings-R',
            'PPZControlSettings-W',
            'PPZControlSettings-D',
            'PPZIntegration-R',
            'PPZIntegration-W',
            'PPZIntegration-D',
            'Rewarding-R',
            'Rewarding-W',
            'Rewarding-D',
            'DailySettlement-R',
            'DailySettlement-W',
            'DailySettlement-D',
            'MonthlyQuarterlySettlement-R',
            'MonthlyQuarterlySettlement-W',
            'MonthlyQuarterlySettlement-D',
            'AnnualSettlement-R',
            'AnnualSettlement-W',
            'AnnualSettlement-D',
            'Documents-R',
            'Documents-W',
            'Documents-D',
            'Reports-R',
            'Reports-W',
            'Reports-D',
            'MobileControllUser',
            'MobileControllPayments',
            'MobileControllProviding',
        ])->delete();
    }

};
